### ISSUE TITLE
x11-drivers/nvidia-drivers-340.108-r1: migrate to virtual/opencl-3

### ISSUE THREAD

**Issue by ionenwks** [achurch/noglvnd#1]
One big reason people will want to use this overlay is for nvidia 340 which never got libglvnd support and ::gentoo removed earlier (all the masks are gone too, so no longer need unmasking).

However it hard depends on eselect-open**c**l, which isn't in this overlay and got removed as well. Rather than adding it here, it'd probably be better to go with the formerly proposed migration that never got pushed. See gentoo-dev post:
https://archives.gentoo.org/gentoo-dev/message/9c2da71a159d860aea32ff2b1300ae84

Changing `app-eselect/eselect-opencl` to `>=virtual/opencl-3` and removing `"${ROOT}"/usr/bin/eselect opencl set --use-old nvidia` line should be enough (Edit: or also check for kernel_linux? () like gentoo-dev mention if want to be pedantic).

I don't have the hardware to test this but "read" that it works, only opening this issue on behalf of others,

**Comment by achurch** [comment]
SGTM. I'll re-add nvidia-drivers-340 which got removed in the sync and apply that change.

**Comment by achurch** [comment]
I don't use the 340 series myself so I can't verify the change; please reopen if there are any problems.

**Comment by ionenwks** [comment]
> I don't use the 340 series myself so I can't verify the change; please reopen if there are any problems.

Yeah I've let users I was talking to know about this, hopefully will offer fixes here themselves if there's further problems. Thanks.

Edit: Also I've had confirmation that it builds and driver is usable, no idea for opencl but it doesn't cause trouble at least. For anyone reading, reminder you can emerge -1 opencl-icd-loader (very small) to satisfy virtual/opencl and avoid the ruby dependency.
