### ISSUE TITLE
xorg-server ebuild needs update to 1.20.10-r2

### ISSUE THREAD

**Issue by KosmiK2001** [achurch/noglvnd#3]
[ebuild     U  ] x11-base/xorg-server-1.20.10-r2:0/1.20.10::gentoo [1.20.10:0/1.20.10::noglvnd] USE="dmx elogind suid udev wayland xorg -debug -doc -ipv6 -kdrive (-libressl) -minimal (-selinux) -systemd -unwind -xcsecurity -xephyr -xnest -xvfb (-libglvnd%)" 0 KiB

**Comment by achurch** [comment]
Done.
