### ISSUE TITLE
Kernels compatability patchsets

### ISSUE THREAD

**Issue by KosmiK2001** [achurch/noglvnd#4]
Hellow there. I found a full (<=5.10) patches for nvidia-drivers.
Here archive.
https://drive.google.com/file/d/1YTDWJtj7n82dYZieEe62iG1_SYfoYUzf/view?usp=sharing
Actually, patches are applied cumulatively:
kernel 5.7 = 5.7 patch
kernel 5.8 = [5.7 + 5.8] patch
an so on ...
<= 5.10 kernel
It seems to me that the ebuild needs to add kernel checking and apply patches accordingly.
At the moment I am on 5.10 kernel and 8800gt. Everything works. (for now :-) )

**Comment by KosmiK2001** [comment]
(uvm+plus all_in_5.10.patch) support patch for ebuild
[https://drive.google.com/file/d/1ZwCNd4-lIAsF9CqPnfqHl3Bw7xF7jjCv/view?usp=sharing](url) 
I hope you figure out what and where .. :-)

also needed nvidia-uvm.conf
https://drive.google.com/file/d/1v6i9f9zj4upumTED7G6If698JC4REAMQ/view?usp=sharing

**Comment by achurch** [comment]
Thanks for the patches! I'll take a look when I have a moment.

**Comment by KosmiK2001** [comment]
amm, any progress?

**Comment by achurch** [comment]
Sorry about the delay; I've had some real-life issues to deal with. I won't be able to test the patches myself, but I'll go ahead and get them committed.
